export function getDom() {
  const canvas = document.querySelector("#game");

  if (!canvas) {
    throw new Error("Canvas #game nicht gefunden");
  }

  return {
    canvas,
    ctx: canvas.getContext("2d"),
    menu: document.querySelector("#menu"),
    gamePanel: document.querySelector("#gamePanel"),
    startBtn: document.querySelector("#startBtn"),
    pauseBtn: document.querySelector("#pauseBtn"),
    message: document.querySelector("#message"),
    touchControls: document.querySelector("#touchControls"),
    touchStick: document.querySelector("#touchStick"),
    touchKnob: document.querySelector("#touchKnob"),
    touchFire: document.querySelector("#touchFire"),
    touchSpecial: document.querySelector("#touchSpecial"),
    playerNameInput: document.querySelector("#playerName"),
    moveHint: document.querySelector("#moveHint"),
    aimHint: document.querySelector("#aimHint"),
    fireHint: document.querySelector("#fireHint"),
    specialHint: document.querySelector("#specialHint"),
    heroName: document.querySelector("#heroName"),
    waveText: document.querySelector("#wave"),
    scoreText: document.querySelector("#score"),
    highScoreText: document.querySelector("#highScore"),
    difficultyText: document.querySelector("#difficultyHud"),
    menuHighScoreText: document.querySelector("#menuHighScore"),
    coinCount: document.querySelector("#coinCount"),
    testIdBtn: document.querySelector("#testIdBtn"),
    testIdText: document.querySelector("#testIdText"),
    multiplayerTestBtn: document.querySelector("#multiplayerTestBtn"),
    multiplayerStatus: document.querySelector("#multiplayerStatus"),
    createLobbyBtn: document.querySelector("#createLobbyBtn"),
    joinLobbyBtn: document.querySelector("#joinLobbyBtn"),
    leaveLobbyBtn: document.querySelector("#leaveLobbyBtn"),
    coopStartBtn: document.querySelector("#coopStartBtn"),
    coopStartText: document.querySelector("#coopStartText"),
    lobbyCodeInput: document.querySelector("#lobbyCodeInput"),
    lobbyCodeText: document.querySelector("#lobbyCodeText"),
    lobbyPlayersText: document.querySelector("#lobbyPlayersText"),
    lobbyNames: document.querySelector("#lobbyNames"),
    endbossBtn: document.querySelector("#endbossBtn"),
    companionReward: document.querySelector("#companionReward"),
    rewardEquipBtn: document.querySelector("#rewardEquipBtn"),
    rewardCloseBtn: document.querySelector("#rewardCloseBtn"),
    testPanel: document.querySelector("#testPanel"),
    testPanelGame: document.querySelector("#testPanelGame"),
    testPanelUser: document.querySelector("#testPanelUser"),
    testCoinsBtn: document.querySelector("#testCoinsBtn"),
    testMaxCoinsBtn: document.querySelector("#testMaxCoinsBtn"),
    testWave10Btn: document.querySelector("#testWave10Btn"),
    testWave20Btn: document.querySelector("#testWave20Btn"),
    testUnlockBtn: document.querySelector("#testUnlockBtn"),
    testMaxHeroBtn: document.querySelector("#testMaxHeroBtn"),
    testHealBtn: document.querySelector("#testHealBtn"),
    testSpecialBtn: document.querySelector("#testSpecialBtn"),
    testEndbossBtn: document.querySelector("#testEndbossBtn"),
    testGodModeBtn: document.querySelector("#testGodModeBtn"),
    testClearThreatsBtn: document.querySelector("#testClearThreatsBtn"),
    testDefeatRobotsBtn: document.querySelector("#testDefeatRobotsBtn"),
    testScoreBtn: document.querySelector("#testScoreBtn"),
    testPickupHealBtn: document.querySelector("#testPickupHealBtn"),
    testPickupDamageBtn: document.querySelector("#testPickupDamageBtn"),
    testPickupSpeedBtn: document.querySelector("#testPickupSpeedBtn"),
    testBlindnessBtn: document.querySelector("#testBlindnessBtn"),
    testCopyStateBtn: document.querySelector("#testCopyStateBtn"),
    testDebugStatus: document.querySelector("#testDebugStatus"),
    testGameHealBtn: document.querySelector("#testGameHealBtn"),
    testGameSpecialBtn: document.querySelector("#testGameSpecialBtn"),
    testGameCoinsBtn: document.querySelector("#testGameCoinsBtn"),
    testGameWave10Btn: document.querySelector("#testGameWave10Btn"),
    testGameWave20Btn: document.querySelector("#testGameWave20Btn"),
    testGameEndbossBtn: document.querySelector("#testGameEndbossBtn"),
    testGameBossPhaseBtn: document.querySelector("#testGameBossPhaseBtn"),
    testGameBossQuakeBtn: document.querySelector("#testGameBossQuakeBtn"),
    testGameBossMaskBtn: document.querySelector("#testGameBossMaskBtn"),
    testGameBossBatsBtn: document.querySelector("#testGameBossBatsBtn"),
    testGameGodModeBtn: document.querySelector("#testGameGodModeBtn"),
    testGameClearThreatsBtn: document.querySelector("#testGameClearThreatsBtn"),
    testGameDefeatRobotsBtn: document.querySelector("#testGameDefeatRobotsBtn"),
    testGameScoreBtn: document.querySelector("#testGameScoreBtn"),
    testGamePickupHealBtn: document.querySelector("#testGamePickupHealBtn"),
    testGameBlindnessBtn: document.querySelector("#testGameBlindnessBtn"),
    testGameCopyStateBtn: document.querySelector("#testGameCopyStateBtn"),
    testGameDebugStatus: document.querySelector("#testGameDebugStatus"),
    heroMenuBtn: document.querySelector("#heroMenuBtn"),
    shopMenuBtn: document.querySelector("#shopMenuBtn"),
    heroPanel: document.querySelector("#heroPanel"),
    shopPanel: document.querySelector("#shopPanel"),
    heroList: document.querySelector("#heroList"),
    shopList: document.querySelector("#shopList"),
    heroDetails: document.querySelector("#heroDetails"),
    healthBar: document.querySelector("#healthBar"),
    specialBar: document.querySelector("#specialBar"),
    leaderboardMode: document.querySelector("#leaderboardMode"),
    leaderboardFilter: document.querySelector("#leaderboardFilter"),
    leaderboardList: document.querySelector("#leaderboardList")
  };
}
